In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('join_wpdx_with_ipc_wide.parquet')

In [3]:
df.columns

Index(['wpdx_id', 'lat_deg', 'lon_deg', 'country_id', 'country_name', 'adm1',
       'adm1_pcode', 'adm2', 'adm2_pcode', 'status_clean',
       'water_source_category', 'water_tech_category', 'local_population',
       'assigned_population', 'subjective_quality', 'is_urban',
       'distance_to_city', 'distance_to_town', 'distance_to_primary',
       'distance_to_secondary', 'distance_to_tertiary', 'facility_type',
       'criticality', 'usage_cap', 'pressure', 'install_year', 'report_date',
       'staleness', 'days_since_report', 'rehab_priority',
       'fecal_coliform_presence', 'water_tech_clean', 'management_clean',
       'Date of analysis', 'Country', 'Total country population', 'Level 1',
       'Area', 'Validity period', 'From', 'To', 'phase_1_number',
       'phase_1_percentage', 'phase_2_number', 'phase_2_percentage',
       'phase_3_number', 'phase_3_percentage', 'phase_3plus_number',
       'phase_3plus_percentage', 'phase_4_number', 'phase_4_percentage',
       'phase_5_number', 'phase_5_percentage', 'phase_all_number',
       'phase_all_percentage', 'adm1_pcode_manual', 'adm2_pcode_manual'],
      dtype='object')

In [37]:
df.isnull().sum()/len(df)

wpdx_id                     0.000000
lat_deg                     0.000000
lon_deg                     0.000000
country_id                  0.000000
country_name                0.000000
adm1                        0.000000
adm1_pcode                  0.000000
adm2                        0.000000
adm2_pcode                  0.000000
status_clean                0.000000
water_source_category       0.044090
water_tech_category         0.222008
local_population            0.102817
assigned_population         0.102817
subjective_quality          0.599760
is_urban                    0.538983
distance_to_city            0.001297
distance_to_town            0.000000
distance_to_primary         0.000000
distance_to_secondary       0.000000
distance_to_tertiary        0.000000
facility_type               0.000000
criticality                 0.116018
usage_cap                   0.045478
pressure                    0.120107
install_year                0.344995
report_date                 0.000000
staleness                   0.000000
days_since_report           0.000000
rehab_priority              0.742906
fecal_coliform_presence     0.975485
water_tech_clean            0.212320
management_clean            0.362057
Date of analysis            1.000000
Country                     1.000000
Total country population    1.000000
Level 1                     1.000000
Area                        1.000000
Validity period             1.000000
From                        1.000000
To                          1.000000
phase_1_number              1.000000
phase_1_percentage          1.000000
phase_2_number              1.000000
phase_2_percentage          1.000000
phase_3_number              1.000000
phase_3_percentage          1.000000
phase_3plus_number          1.000000
phase_3plus_percentage      1.000000
phase_4_number              1.000000
phase_4_percentage          1.000000
phase_5_number              1.000000
phase_5_percentage          1.000000
phase_all_number            1.000000
phase_all_percentage        1.000000
adm1_pcode_manual           0.060001
adm2_pcode_manual           0.060001
dtype: float64

In [4]:
df_water = df[['wpdx_id','country_id','country_name','local_population','assigned_population','subjective_quality','report_date','adm1_pcode_manual','adm2_pcode_manual','criticality','status_clean']]

In [5]:
df_water.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426427 entries, 0 to 426426
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   wpdx_id              426427 non-null  object
 1   country_id           426427 non-null  object
 2   country_name         426427 non-null  object
 3   local_population     382583 non-null  float64
 4   assigned_population  382583 non-null  float64
 5   subjective_quality   170673 non-null  object
 6   report_date          426427 non-null  object
 7   adm1_pcode_manual    400841 non-null  object
 8   adm2_pcode_manual    400841 non-null  object
 9   criticality          376954 non-null  float64
 10  status_clean         426427 non-null  object
dtypes: float64(3), object(8)
memory usage: 35.8+ MB

In [ ]:
# due paesi senza p_code

coverage_pcodes = df_water.groupby('country_id').agg(
    righe_totali=('adm1_pcode_manual', 'size'),
    righe_adm1=('adm1_pcode_manual', 'count'),
    righe_adm2=('adm2_pcode_manual', 'count'),
)

coverage_pcodes['pct_adm1'] = coverage_pcodes['righe_adm1'] / coverage_pcodes['righe_totali']
coverage_pcodes['pct_adm2'] = coverage_pcodes['righe_adm2'] / coverage_pcodes['righe_totali']

coverage_pcodes

            righe_totali  righe_adm1  righe_adm2  pct_adm1  pct_adm2
country_id
BGD                20084       20046       20046  0.998108  0.998108
CAF                 2362        2348        2348  0.994073  0.994073
ETH                24488       24248       24248  0.990199  0.990199
GHA                26367       26210       26210  0.994046  0.994046
GTM                  442         431         431  0.975113  0.975113
HTI                 6276        6231        6231  0.992830  0.992830
KEN                21953       21822       21822  0.994033  0.994033
LBR                28452       28379       28379  0.997434  0.997434
MWI                 1884        1877        1877  0.996285  0.996285
NGA                99245       99062       99062  0.998156  0.998156
RWA                 6114           0           0  0.000000  0.000000
SLE                29614       29431       29431  0.993820  0.993820
SSD                 6099        5739        5739  0.940974  0.940974
SWZ                12546       12537       12537  0.999283  0.999283
TZA                17518           0           0  0.000000  0.000000
UGA                98767       98605       98605  0.998360  0.998360
ZMB                 6643        6311        6311  0.950023  0.950023
ZWE                17573       17564       17564  0.999488  0.999488

In [6]:
df_water['status_clean'].value_counts()

status_clean
Non-Functional                226377
Functional, not in use         81937
Functional, needs repair       71504
Functional                     29756
Non-Functional, dry season     10633
Others                          3175
Abandoned/Decommissioned        3045
Name: count, dtype: int64

In [7]:
df_water['subjective_quality'].value_counts(normalize=True)

subjective_quality
Acceptable quality                                      0.428035
Crystal clear                                           0.125585
Soft                                                    0.081319
intermediate                                            0.043463
low                                                     0.039848
                                                          ...
Taste: not yet Color: not yet                           0.000006
Taste: Dry well Color: Normal                           0.000006
Taste: rust taste Color: Brown                          0.000006
Taste: Good Color: not clear  it has brown particles    0.000006
Foamy No smell                                          0.000006
Name: proportion, Length: 1018, dtype: float64

In [8]:
df_water['country_name'].unique()

array(['Bangladesh', 'Central African Republic', 'Ethiopia', 'Ghana',
       'Guatemala', 'Haiti', 'Kenya', 'Liberia', 'Malawi', 'Nigeria',
       'Rwanda', 'Sierra Leone', 'South Sudan', 'Eswatini', 'Tanzania',
       'Uganda', 'Zambia', 'Zimbabwe'], dtype=object)

In [9]:
df_water['report_date'] = pd.to_datetime(df_water['report_date'])

C:\Users\skywa\AppData\Local\Temp\ipykernel_13080\2002713739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_water['report_date'] = pd.to_datetime(df_water['report_date'])

In [10]:
df_water['report_date'].min(), df_water['report_date'].max()

(Timestamp('1900-01-01 00:00:00'), Timestamp('2025-12-07 00:00:00'))

In [11]:
df_water['report_date'].value_counts().sort_index()

report_date
1900-01-01      1
1905-06-30      1
1971-03-11      1
1973-05-12      1
1973-05-27      4
             ...
2025-12-03     71
2025-12-04     27
2025-12-05     75
2025-12-06    113
2025-12-07     58
Name: count, Length: 6425, dtype: int64

In [12]:
#df_water.to_parquet('df_water.parquet', index=False)

In [13]:
df_water['status_clean'].value_counts()

status_clean
Non-Functional                226377
Functional, not in use         81937
Functional, needs repair       71504
Functional                     29756
Non-Functional, dry season     10633
Others                          3175
Abandoned/Decommissioned        3045
Name: count, dtype: int64

In [14]:
functional_map = {
    'Functional': 'Functional',
    'Functional, needs repair': 'Functional',
    'Functional, not in use': 'Functional',
    'Non-Functional': 'Non-Functional',
    'Non-Functional, dry season': 'Non-Functional',
    'Abandoned/Decommissioned': 'Non-Functional',
    'Others': 'Non-Functional',
}

df_water['functional_binary'] = df_water['status_clean'].map(functional_map)

C:\Users\skywa\AppData\Local\Temp\ipykernel_13080\2454378519.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_water['functional_binary'] = df_water['status_clean'].map(functional_map)

In [15]:
df_water['functional_binary'].value_counts()

functional_binary
Non-Functional    243230
Functional        183197
Name: count, dtype: int64

In [16]:
df_water['subjective_quality'].value_counts()

subjective_quality
Acceptable quality                                      73054
Crystal clear                                           21434
Soft                                                    13879
intermediate                                             7418
low                                                      6801
                                                        ...
Taste: not yet Color: not yet                               1
Taste: Dry well Color: Normal                               1
Taste: rust taste Color: Brown                              1
Taste: Good Color: not clear  it has brown particles        1
Foamy No smell                                              1
Name: count, Length: 1018, dtype: int64

In [ ]:
df_water['subjective_quality'].isnull().sum()/len(df_water) # alta percentuale valori mancanti

np.float64(0.5997603341251844)

In [ ]:
df_water_2019 = df_water[df_water['report_date']>='2019-01-01']
df_water_2019['subjective_quality'].isnull().sum()/len(df_water_2019)

np.float64(0.7388003351365888)

#### Aggregazione per area geografica (admin2) e per data (cumulativa per report_date)

In [17]:
# ── 1. Tutti i checkpoint (zone × date distinte) ────────────────────────────
checkpoints = df_water[
    ['country_id', 'adm1_pcode_manual', 'adm2_pcode_manual', 'report_date']
].drop_duplicates()

# ── 2. Attributi per punto d'acqua ──────────────────────────────────────────
points = df_water

# ── 3. Per ogni checkpoint, tutti i punti con report_date <= checkpoint ──────
merged = checkpoints.merge(
    points,
    on=['country_id', 'adm1_pcode_manual', 'adm2_pcode_manual'],
    suffixes=('_checkpoint', '_point')
)
merged = merged[merged['report_date_point'] <= merged['report_date_checkpoint']]

# ── 4. Aggregazione cumulativa di tutto insieme ──────────────────────────────
df_water_agg = (
    merged
    .groupby(['country_id', 'adm1_pcode_manual', 'adm2_pcode_manual', 'report_date_checkpoint'])
    .agg(
        local_population=('local_population', 'sum'),
        assigned_population=('assigned_population', 'sum'),
        water_points_count=('wpdx_id', 'nunique'),
        criticality = ('criticality','mean'),
        functional_points_count=('wpdx_id', lambda x: x[merged.loc[x.index, 'functional_binary'] == 'Functional'].nunique()),

    )
    .reset_index()
    .rename(columns={'report_date_checkpoint': 'report_date'})
)

In [20]:
df_water_agg

,country_id,adm1_pcode_manual,adm2_pcode_manual,report_date,local_population,assigned_population,water_points_count,criticality,functional_points_count
0,BGD,BD10,BD1009,2014-02-12,19394.0,17841.0,6,0.889858,2
1,BGD,BD10,BD1009,2014-03-12,49696.0,41637.0,14,0.870623,2
2,BGD,BD10,BD1009,2014-04-12,76063.0,64864.0,23,0.868189,3
3,BGD,BD10,BD1009,2014-05-12,147037.0,97268.0,33,0.808823,3
4,BGD,BD10,BD1009,2014-06-12,185837.0,122493.0,34,0.804155,3
...,...,...,...,...,...,...,...,...,...
33903,ZWE,ZW19,ZW1924,2013-10-28,15386.0,1618.0,3,0.150892,0
33904,ZWE,ZW19,ZW1924,2013-11-27,19393.0,2133.0,4,0.145300,0
33905,ZWE,ZW19,ZW1924,2013-12-21,20965.0,2493.0,5,0.162042,0
33906,ZWE,ZW19,ZW1924,2014-10-01,30898.0,3195.0,6,0.146814,0
33907,ZWE,ZW19,ZW1924,2022-09-17,42230.0,4013.0,7,0.136153,0

In [27]:
url_semiwide = "https://raw.githubusercontent.com/Federicomartinelli99/HERO/refs/heads/main/ipc/ipc_global_area_wide_pcoded.csv"
df_ipc = pd.read_csv(url_semiwide, parse_dates = ['From', 'To'], dayfirst = True)

In [70]:
country_match = set(df_ipc['Country'].unique()) & set(df_water['country_id'].unique())

#### Join con dataset ipc a livello admin2

In [29]:
import numpy as np


df_water_agg['report_date'] = pd.to_datetime(df_water_agg['report_date'])

# 1. Creiamo il set univoco di intervalli IPC a livello Admin 2
df_ipc_adm2 = df_ipc[['Country', 'From', 'To', 'adm1_pcode', 'adm2_pcode']].drop_duplicates().reset_index(drop=True)
df_ipc_adm2['adm2_row_id'] = df_ipc_adm2.index

# 2. Merge Geografico (Left Join)
df_geo_merged = df_ipc_adm2.merge(
    df_water_agg,
    left_on=['Country', 'adm1_pcode', 'adm2_pcode'],
    right_on=['country_id', 'adm1_pcode_manual', 'adm2_pcode_manual'],
    how='left'
)

# 3. Calcolo della distanza temporale
def calculate_distance(df):
    mask_inside = (df['report_date'] >= df['From']) & (df['report_date'] <= df['To'])
    dist_from = (df['report_date'] - df['From']).dt.days.abs()
    dist_to = (df['report_date'] - df['To']).dt.days.abs()
    return np.where(mask_inside, 0, np.minimum(dist_from, dist_to))

df_geo_merged['distanza_giorni'] = calculate_distance(df_geo_merged)

# 4. Selezione per ogni intervallo Admin 2 (adm2_row_id)

# A. Match perfetti (distanza 0): teniamo il checkpoint più recente nell'intervallo
mask_perfect = df_geo_merged['distanza_giorni'] == 0
df_perfect_candidates = df_geo_merged[mask_perfect].sort_values(by=['adm2_row_id', 'report_date'])
df_perfect_avg = df_perfect_candidates.drop_duplicates('adm2_row_id', keep='last')[
    ['adm2_row_id', 'local_population', 'assigned_population', 'water_points_count',
     'functional_points_count', 'criticality', 'report_date', 'distanza_giorni']
]

# B. Recupero per prossimità (Orfani): prendiamo il più vicino solo se non c'è un match perfetto
matched_ids = df_perfect_avg['adm2_row_id'].unique()
df_orphans = df_geo_merged[
    (~df_geo_merged['adm2_row_id'].isin(matched_ids)) &
    (df_geo_merged['water_points_count'].notna())
].copy()

df_orphans_closest = df_orphans.sort_values(by=['adm2_row_id', 'distanza_giorni']).drop_duplicates('adm2_row_id', keep='first')

# C. Unione dei risultati mappati agli ID univoci di df_ipc_adm2
df_idp_final_map = pd.concat([
    df_perfect_avg,
    df_orphans_closest[['adm2_row_id', 'local_population', 'assigned_population', 'water_points_count',
    'functional_points_count', 'criticality', 'report_date', 'distanza_giorni']]
])

# 5. Integrazione finale nel dataset originale
df_ipc_adm2_integrated = df_ipc_adm2.merge(
    df_idp_final_map[['adm2_row_id', 'local_population', 'assigned_population', 'water_points_count',
    'functional_points_count', 'criticality', 'report_date', 'distanza_giorni']],
    on='adm2_row_id',
    how='left'
)

df_final_integrated = df_ipc.merge(
    df_ipc_adm2_integrated[['Country', 'From', 'To', 'adm1_pcode', 'adm2_pcode', 'local_population', 'assigned_population', 'water_points_count',
    'functional_points_count', 'criticality', 'report_date', 'distanza_giorni']],
    on=['Country', 'From', 'To', 'adm1_pcode','adm2_pcode'],
    how='left'
)

# --- VERIFICA ---
print(f"Verifica righe: {len(df_final_integrated)} (Originale IPC: {len(df_ipc)})")
print(f"Righe con dato acqua integrato: {df_final_integrated['water_points_count'].notna().sum()}")

Verifica righe: 72213 (Originale IPC: 72213)
Righe con dato acqua integrato: 24000

##### Copertura dato punti accesso acqua per paese

In [42]:
coverage_by_country = (
    df_final_integrated
    .groupby('Country')['water_points_count']
    .agg(
        righe_totali='size',
        righe_con_acqua='count'  # 'count' su una Series ignora i NaN
    )
)
coverage_by_country['pct_coperto'] = (
    coverage_by_country['righe_con_acqua'] / coverage_by_country['righe_totali']
)
coverage_by_country = coverage_by_country.sort_values('pct_coperto', ascending=False)

print(coverage_by_country)

         righe_totali  righe_con_acqua  pct_coperto
Country
NGA             15900            15500     0.974843
SLE               344              326     0.947674
SSD              3631             3298     0.908290
UGA               442              340     0.769231
ZMB              1315              859     0.653232
ZWE               360              234     0.650000
GHA              2384             1522     0.638423
CAF              1761             1026     0.582624
ETH               721              407     0.564494
BGD               218               64     0.293578
MWI               737              209     0.283582
HTI               737              110     0.149254
SWZ               177               24     0.135593
GTM               470               42     0.089362
KEN               721               39     0.054092
BDI               264                0     0.000000
BEN              1540                0     0.000000
CMR              1276                0     0.000000
AGO                80                0     0.000000
AFG              1321                0     0.000000
GNB               180                0     0.000000
GMB               136                0     0.000000
GIN               538                0     0.000000
DOM               244                0     0.000000
ECU                72                0     0.000000
COD              3688                0     0.000000
CPV               286                0     0.000000
DJI               150                0     0.000000
CIV               726                0     0.000000
BFA               762                0     0.000000
MLI              1139                0     0.000000
MDG               954                0     0.000000
LBR               139                0     0.000000
LSO               220                0     0.000000
HND               339                0     0.000000
LBN               665                0     0.000000
PSE                58                0     0.000000
PAK               836                0     0.000000
NER              1614                0     0.000000
NAM               280                0     0.000000
MOZ              1526                0     0.000000
MRT               992                0     0.000000
SLV               106                0     0.000000
SDN              4792                0     0.000000
TCD              1566                0     0.000000
SOM             10005                0     0.000000
SEN               996                0     0.000000
TGO               670                0     0.000000
TZA               270                0     0.000000
TLS                56                0     0.000000
ZAF                68                0     0.000000
YEM              3741                0     0.000000

In [71]:
df_country_match = df_final_integrated[df_final_integrated['Country'].isin(country_match)]

In [72]:
df_country_match[['local_population','assigned_population','water_points_count','functional_points_count','criticality','report_date','distanza_giorni']].isnull().sum()/len(df_country_match)

local_population           0.208626
assigned_population        0.208626
water_points_count         0.208626
functional_points_count    0.208626
criticality                0.222442
report_date                0.208626
distanza_giorni            0.208626
dtype: float64

In [74]:
df_country_match.groupby('Country')['distanza_giorni'].mean()

Country
BGD    1804.125000
CAF    1349.417154
ETH     629.090909
GHA    1378.339685
GTM    1165.404762
HTI    1094.545455
KEN    1379.000000
LBR            NaN
MWI     945.732057
NGA    1428.563290
SLE    1121.257669
SSD     801.714372
SWZ     441.041667
TZA            NaN
UGA     495.641176
ZMB     599.995343
ZWE      79.175214
Name: distanza_giorni, dtype: float64

In [75]:
df_water[df_water['country_id'] == 'LBR']['adm2_pcode_manual'].unique()

array(['LR0401', 'LR1103', 'LR0901', 'LR1101', 'LR0104', 'LR0503',
       'LR0603', 'LR1213', 'LR0209', 'LR1204', 'LR1211', 'LR1214',
       'LR0802', None, 'LR0903', 'LR0202', 'LR1505', 'LR0712', 'LR0701',
       'LR0717', 'LR0704', 'LR1509', 'LR1504', 'LR1002', 'LR1006',
       'LR0710', 'LR0716', 'LR1004', 'LR1003', 'LR1001', 'LR1005',
       'LR0406', 'LR0402', 'LR1503', 'LR1408', 'LR1404', 'LR1402',
       'LR1406', 'LR0405', 'LR0608', 'LR1306', 'LR1308', 'LR0606',
       'LR0502', 'LR0501', 'LR0505', 'LR0408', 'LR0904', 'LR0407',
       'LR1102', 'LR1104', 'LR0101', 'LR1105', 'LR0102', 'LR0902',
       'LR0103', 'LR0207', 'LR0304', 'LR0303', 'LR1405', 'LR1206',
       'LR0404', 'LR1403', 'LR0403', 'LR1216', 'LR0204', 'LR0210',
       'LR0211', 'LR0201', 'LR0203', 'LR0205', 'LR1210', 'LR0602',
       'LR0601', 'LR1203', 'LR1208', 'LR1201', 'LR1202', 'LR0504',
       'LR0302', 'LR0305', 'LR0306', 'LR0208', 'LR0212', 'LR0206',
       'LR0301', 'LR0804', 'LR0807', 'LR1209', 'LR1217', 'LR1207',
       'LR1212', 'LR1215', 'LR1205', 'LR0805', 'LR0801', 'LR0806',
       'LR0803', 'LR0715', 'LR0713', 'LR0711', 'LR1517', 'LR1512',
       'LR1301', 'LR0607', 'LR0605', 'LR0707', 'LR1511', 'LR1310',
       'LR1506', 'LR1302', 'LR1515', 'LR1502', 'LR1407', 'LR1401',
       'LR1513', 'LR1508', 'LR1516', 'LR0708', 'LR0703', 'LR0714',
       'LR0702', 'LR1510', 'LR0705', 'LR0718', 'LR0706', 'LR0709',
       'LR1507', 'LR1307', 'LR1007', 'LR0604', 'LR1309', 'LR1303',
       'LR1304', 'LR1514', 'LR1305'], dtype=object)

In [76]:
df_ipc[df_ipc['Country'] == 'LBR']['adm2_pcode'].unique()

array(['LR01', 'LR02', 'LR03', 'LR04', 'LR05', 'LR06', 'LR07', 'LR08',
       'LR09', 'LR10', 'LR11', 'LR12', 'LR13', 'LR14', 'LR15'],
      dtype=object)

In [82]:
(set(df_water[df_water['country_id'] == 'LBR']['adm2_pcode_manual'].unique())) & (set(df_ipc[df_ipc['Country'] == 'LBR']['adm2_pcode'].unique()))

set()

In [45]:
df2 = pd.read_csv('Water_Point_Data_Exchange.csv')

C:\Users\skywa\AppData\Local\Temp\ipykernel_13080\1651053022.py:1: DtypeWarning: Columns (15,16,18,20,21,23,24,26,27,28,31,32,44,50,60,61,62,63) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('Water_Point_Data_Exchange.csv')

In [46]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440270 entries, 0 to 440269
Data columns (total 73 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   row_id                       440270 non-null  float64
 1   #source                      440270 non-null  object
 2   #lat_deg                     440270 non-null  object
 3   #lon_deg                     440270 non-null  object
 4   #report_date                 440270 non-null  object
 5   #status_id                   440270 non-null  object
 6   #water_source_clean          421390 non-null  object
 7   #water_source_category       421390 non-null  object
 8   #water_tech_clean            349613 non-null  object
 9   #water_tech_category         345482 non-null  object
 10  #facility_type               440270 non-null  object
 11  #clean_country_name          440270 non-null  object
 12  #clean_country_id            440270 non-null  object
 13  #clean_adm1                  440270 non-null  object
 14  #clean_adm2                  440270 non-null  object
 15  #clean_adm3                  286566 non-null  object
 16  #clean_adm4                  131241 non-null  object
 17  #install_year                289737 non-null  float64
 18  #installer                   70029 non-null   object
 19  #rehab_year                  358 non-null     float64
 20  #rehabilitator               349 non-null     object
 21  #management_clean            274639 non-null  object
 22  #status_clean                440270 non-null  object
 23  #pay_clean                   190042 non-null  object
 24  #fecal_coliform_presence     10454 non-null   object
 25  #fecal_coliform_value        4549 non-null    float64
 26  #subjective_quality_clean    153849 non-null  object
 27  #activity_id                 233330 non-null  object
 28  #scheme_id                   32565 non-null   object
 29  #wpdx_id                     440270 non-null  object
 30  #notes                       216110 non-null  object
 31  #orig_lnk                    86308 non-null   object
 32  #photo_lnk                   183881 non-null  object
 33  #country_id                  428724 non-null  object
 34  #data_lnk                    440270 non-null  object
 35  #distance_to_primary_road    440270 non-null  object
 36  #distance_to_secondary_road  440270 non-null  object
 37  #distance_to_tertiary_road   440270 non-null  object
 38  #distance_to_city            439717 non-null  object
 39  #distance_to_town            440270 non-null  object
 40  water_point_history          440270 non-null  object
 41  local_population_1km         396244 non-null  float64
 42  water_point_population       396244 non-null  float64
 43  rehab_priority               109895 non-null  float64
 44  #pop_who_would_gain_access   88241 non-null   object
 45  crucialness_score            388663 non-null  object
 46  pressure_score               386919 non-null  object
 47  usage_capacity               420798 non-null  float64
 48  days_since_report            440270 non-null  float64
 49  staleness_score              440270 non-null  object
 50  latest_record                440266 non-null  object
 51  location_id                  440270 non-null  float64
 52  is_urban                     440270 non-null  bool
 53  cluster_size                 440270 non-null  int64
 54  #country_name                428724 non-null  object
 55  #water_source                420542 non-null  object
 56  #water_tech                  269970 non-null  object
 57  #status                      311516 non-null  object
 58  #adm1                        398697 non-null  object
 59  #adm2                        389305 non-null  object
 60  #adm3                        60321 non-null   object
 61  #management                  276512 non-null  object
 62  #pay                         186810 non-null  object
 63  #subjective_quality          170673 non-null  object
 64  New Georeferenced Column     440270 non-null  object
 65  lat_lon_deg                  440270 non-null  object
 66  public_data_source           440270 non-null  object
 67  converted                    326200 non-null  object
 68  count                        440270 non-null  int64
 69  created_timestamp            440270 non-null  object
 70  updated_timestamp            440270 non-null  object
 71  is_duplicate                 25640 non-null   object
 72  dataset_title                440270 non-null  object
dtypes: bool(1), float64(10), int64(2), object(60)
memory usage: 242.3+ MB

In [47]:
df2['crucialness_score'] = df2['crucialness_score'].str.replace(',','.').astype('float32')

In [49]:
df2['#wpdx_id'].nunique()

440270