In [1]:
import pandas as pd

#carico dataset merged_adm1_wide.parquet
df = pd.read_parquet("../../data/merged/merged_adm1_wide.parquet")
df

,Country,location_name_full,Level 1,Area,adm1_pcode,adm2_pcode,From,To,Validity period,Date of analysis,...,gdelt_verbal_coop_tone,gdelt_material_coop_events,gdelt_material_coop_mentions,gdelt_material_coop_tone,gdelt_verbal_conflict_events,gdelt_verbal_conflict_mentions,gdelt_verbal_conflict_tone,gdelt_material_conflict_events,gdelt_material_conflict_mentions,gdelt_material_conflict_tone
0,AFG,Afghanistan,Kabul,None,AF01,,2017-08-01,2017-11-30 23:59:59,current,2017-08-01T00:00:00,...,-2.391549,6228.0,34053.0,-3.335023,8278.0,47734.0,-4.895209,13942.0,91166.0,-6.719388
1,AFG,Afghanistan,Kabul,None,AF01,,2018-08-01,2018-10-31 23:59:59,current,2018-08-01T00:00:00,...,-2.347104,3932.0,22156.0,-3.595366,5194.0,31849.0,-5.099749,10149.0,67189.0,-6.445504
2,AFG,Afghanistan,Kabul,None,AF01,,2018-11-01,2019-02-28 23:59:59,first projection,2018-11-01T00:00:00,...,-1.569367,6144.0,33598.0,-3.028408,7958.0,45917.0,-3.980824,10838.0,70564.0,-6.438398
3,AFG,Afghanistan,Kabul,None,AF01,,2019-08-01,2019-10-31 23:59:59,current,2019-08-01T00:00:00,...,-2.526242,4653.0,26735.0,-3.212505,7279.0,41200.0,-4.360610,10481.0,64091.0,-5.635617
4,AFG,Afghanistan,Kabul,None,AF01,,2019-11-01,2020-03-31 23:59:59,first projection,2019-11-01T00:00:00,...,-2.124733,8939.0,48517.0,-2.820670,8613.0,46929.0,-3.467968,10706.0,61631.0,-5.146167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10019,ZWE,Zimbabwe,Masvingo,None,ZW18,,2019-06-01,2019-09-30 23:59:59,current,2019-06-01T00:00:00,...,-1.661450,390.0,2041.0,-1.729670,713.0,3780.0,-3.642161,459.0,2506.0,-4.719800
10020,ZWE,Zimbabwe,Masvingo,None,ZW18,,2019-10-01,2019-12-31 23:59:59,first projection,2019-10-01T00:00:00,...,-1.139974,339.0,1867.0,-1.902814,455.0,2562.0,-3.109481,372.0,1866.0,-4.177619
10021,ZWE,Zimbabwe,Masvingo,None,ZW18,,2020-02-01,2020-06-30 23:59:59,current,2020-02-01T00:00:00,...,-1.743440,698.0,3802.0,-1.614034,814.0,4467.0,-3.357042,676.0,3439.0,-4.882919
10022,ZWE,Zimbabwe,Masvingo,None,ZW18,,2020-10-01,2020-12-31 23:59:59,current,2020-10-01T00:00:00,...,-0.543956,240.0,1348.0,-0.123948,280.0,1469.0,-2.400386,204.0,987.0,-3.927138
10023,ZWE,Zimbabwe,Masvingo,None,ZW18,,2021-01-01,2021-03-31 23:59:59,first projection,2021-01-01T00:00:00,...,-0.809510,344.0,1643.0,-1.243817,238.0,1214.0,-3.012257,357.0,1563.0,-5.265559

In [2]:
import altair as alt
ultimo_aggiornamento = df.groupby(['Country', 'adm1_pcode'])['From'].transform('max')
df["phase_3+"] = df["phase_3_number"] + df["phase_4_number"] + df["phase_5_number"]
df_attuali = pd.melt(df[df["From"] == ultimo_aggiornamento], id_vars=['Country'], value_vars=['phase_3+'])
df_chart = df_attuali.groupby(['Country', "variable"])['value'].sum().reset_index()
df_chart

   Country  variable       value
0      AFG  phase_3+   8407446.0
1      AGO  phase_3+   1604034.0
2      BDI  phase_3+     14992.0
3      BEN  phase_3+    218750.0
4      BFA  phase_3+   1094151.0
5      BGD  phase_3+  15978671.0
6      CAF  phase_3+   2706330.0
7      CIV  phase_3+   1326910.0
8      CMR  phase_3+   2857239.0
9      COD  phase_3+  28911929.0
10     CPV  phase_3+     33539.0
11     DJI  phase_3+    104504.0
12     ECU  phase_3+   2823243.0
13     ETH  phase_3+  14569908.0
14     GHA  phase_3+   1502142.0
15     GIN  phase_3+   1940422.0
16     GMB  phase_3+    243937.0
17     GNB  phase_3+    146034.0
18     GTM  phase_3+   3132867.0
19     HND  phase_3+   1827424.0
20     HTI  phase_3+   5910720.0
21     KEN  phase_3+   3770325.0
22     LBR  phase_3+    684960.0
23     LSO  phase_3+     37345.0
24     MDG  phase_3+    650578.0
25     MLI  phase_3+   1560190.0
26     MOZ  phase_3+    796894.0
27     MRT  phase_3+    549505.0
28     NAM  phase_3+    407921.0
29     NER  phase_3+   2374623.0
30     NGA  phase_3+  27212934.0
31     PAK  phase_3+  11514542.0
32     SDN  phase_3+  19099268.0
33     SEN  phase_3+    518510.0
34     SLE  phase_3+    623673.0
35     SLV  phase_3+    906823.0
36     SOM  phase_3+   5649244.0
37     SSD  phase_3+   8887393.0
38     SWZ  phase_3+    189665.0
39     TCD  phase_3+   2977454.0
40     TGO  phase_3+    332148.0
41     TLS  phase_3+    360907.0
42     TZA  phase_3+    839106.0
43     UGA  phase_3+     56198.0
44     YEM  phase_3+  37140042.0
45     ZAF  phase_3+  11795949.0
46     ZMB  phase_3+   1701303.0
47     ZWE  phase_3+   3380233.0

In [11]:
chart = alt.Chart(df_chart).mark_bar().encode(
    x= alt.X("value:Q", scale=alt.Scale(type="sqrt")),
    y=alt.Y("Country:N", sort="-x"),
    color="variable:N",
    tooltip=['Country', 'variable', 'value']
).properties(width=1000)
chart

alt.Chart(...)